//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainForm.Resources.Views.Home {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_en_US {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_en_US() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MainForm.Resources.Views.Home.Index.en-US", typeof(Index_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Job_no {
            get {
                return ResourceManager.GetString("Job_no", resourceCulture);
            }
        }
        
        internal static string Item_name {
            get {
                return ResourceManager.GetString("Item_name", resourceCulture);
            }
        }
        
        internal static string Item_no {
            get {
                return ResourceManager.GetString("Customer_name", resourceCulture);
            }
        }
        
        internal static string Scheduled_completion_quantity {
            get {
                return ResourceManager.GetString("Scheduled_completion_quantity", resourceCulture);
            }
        }
        
        internal static string Item_description {
            get {
                return ResourceManager.GetString("Item_description", resourceCulture);
            }
        }
        
        internal static string Routing_name {
            get {
                return ResourceManager.GetString("Routing_name", resourceCulture);
            }
        }
        
        internal static string Actually_start_date {
            get {
                return ResourceManager.GetString("Actually_start_date", resourceCulture);
            }
        }
        
        internal static string Actually_completion_date {
            get {
                return ResourceManager.GetString("Actually_completion_date", resourceCulture);
            }
        }
        
        internal static string Actually_completion_quantity {
            get {
                return ResourceManager.GetString("Actually_completion_quantity", resourceCulture);
            }
        }
        
        internal static string Actually_defective_quantity {
            get {
                return ResourceManager.GetString("Actually_defective_quantity", resourceCulture);
            }
        }
    }
}
