//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainForm.Resources.ViewModels.Organize {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FactoryViewModel_en_US {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FactoryViewModel_en_US() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MainForm.Resources.ViewModels.Organize.FactoryViewModel.en-US", typeof(FactoryViewModel_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Factory_id {
            get {
                return ResourceManager.GetString("Factory_id", resourceCulture);
            }
        }
        
        internal static string Business_unit_id {
            get {
                return ResourceManager.GetString("Business_unit_id", resourceCulture);
            }
        }
        
        internal static string Factory_no {
            get {
                return ResourceManager.GetString("Factory_no", resourceCulture);
            }
        }
        
        internal static string Factory_name {
            get {
                return ResourceManager.GetString("Factory_name", resourceCulture);
            }
        }
        
        internal static string Factory_description {
            get {
                return ResourceManager.GetString("Factory_description", resourceCulture);
            }
        }
        
        internal static string Is_enable {
            get {
                return ResourceManager.GetString("Is_enable", resourceCulture);
            }
        }
        
        internal static string Create_by {
            get {
                return ResourceManager.GetString("Create_by", resourceCulture);
            }
        }
        
        internal static string Create_date {
            get {
                return ResourceManager.GetString("Create_date", resourceCulture);
            }
        }
        
        internal static string Last_update_by {
            get {
                return ResourceManager.GetString("Last_update_by", resourceCulture);
            }
        }
        
        internal static string Last_update_date {
            get {
                return ResourceManager.GetString("Last_update_date", resourceCulture);
            }
        }
    }
}
